/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author NirmalaKarim
 */
public class Fasilitas_GUI extends javax.swing.JFrame {

    Input_Fasilitas input = new Input_Fasilitas("fasilitas");
    
    /**
     * Creates new form Fasilitas_GUI
     */
    public Fasilitas_GUI() {
        initComponents();
    }

    /**java
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Identitas_button = new javax.swing.JButton();
        Fasilitas_button = new javax.swing.JButton();
        Lingkungan_button = new javax.swing.JButton();
        Keamanan_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JmlSteker_label = new javax.swing.JLabel();
        jmlcctv_label = new javax.swing.JLabel();
        jmlac_label = new javax.swing.JLabel();
        jmllampu_label = new javax.swing.JLabel();
        jmlkipas_label = new javax.swing.JLabel();
        Jmlkabel_label = new javax.swing.JLabel();
        ssid_label = new javax.swing.JLabel();
        kondisicctv_label = new javax.swing.JLabel();
        JmlSteker_txt = new javax.swing.JTextField();
        jmlkabel_txt = new javax.swing.JTextField();
        jmlcctv_txt = new javax.swing.JTextField();
        jmlkipas_txt = new javax.swing.JTextField();
        jmllampu_txt = new javax.swing.JTextField();
        jmlAc_txt = new javax.swing.JTextField();
        kondisicctv_combo = new javax.swing.JComboBox();
        kondisilampu_label = new javax.swing.JLabel();
        posisisteker_label = new javax.swing.JLabel();
        kondisiac_label = new javax.swing.JLabel();
        kondisikipas_label = new javax.swing.JLabel();
        ssid_combo = new javax.swing.JComboBox();
        kondisikipas_combo = new javax.swing.JComboBox();
        kondisilampu_combo = new javax.swing.JComboBox();
        kondisikabel_combo = new javax.swing.JComboBox();
        posisikabel_combo = new javax.swing.JComboBox();
        kondisikabel_label = new javax.swing.JLabel();
        kondisiac_combo = new javax.swing.JComboBox();
        posisikabel_label = new javax.swing.JLabel();
        posisilampu_label = new javax.swing.JLabel();
        posisikipas_label = new javax.swing.JLabel();
        posisiac_label = new javax.swing.JLabel();
        posisicctv_label = new javax.swing.JLabel();
        kondisisteker_label = new javax.swing.JLabel();
        kondisisteker_combo = new javax.swing.JComboBox();
        posisilampu_combo = new javax.swing.JComboBox();
        posisikipas_combo = new javax.swing.JComboBox();
        posisicctv_combo = new javax.swing.JComboBox();
        posisisteker_combo = new javax.swing.JComboBox();
        posisiac_combo = new javax.swing.JComboBox();
        jmlampu_button = new javax.swing.JButton();
        jmlsteker_button = new javax.swing.JButton();
        jmlkipas_button = new javax.swing.JButton();
        jmlac_button = new javax.swing.JButton();
        ssid_button = new javax.swing.JButton();
        jmlkabel_button = new javax.swing.JButton();
        kondisisteker_button = new javax.swing.JButton();
        kondisilampu_button = new javax.swing.JButton();
        jmlcctv_button = new javax.swing.JButton();
        kondisikipas_button = new javax.swing.JButton();
        kondisiac_button = new javax.swing.JButton();
        posisicctv_button = new javax.swing.JButton();
        kondisikabel_button = new javax.swing.JButton();
        posisiac_button = new javax.swing.JButton();
        posisikipas_button = new javax.swing.JButton();
        posisilampu_button = new javax.swing.JButton();
        posisikabel_button = new javax.swing.JButton();
        posisisteker_button = new javax.swing.JButton();
        kondisicctv_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JmlSteker_label1 = new javax.swing.JLabel();
        jmlcctv_label1 = new javax.swing.JLabel();
        jmlac_label1 = new javax.swing.JLabel();
        jmllampu_label1 = new javax.swing.JLabel();
        jmlkipas_label1 = new javax.swing.JLabel();
        Jmlkabel_label1 = new javax.swing.JLabel();
        ssid_label1 = new javax.swing.JLabel();
        kondisicctv_label1 = new javax.swing.JLabel();
        JmlSteker_txt1 = new javax.swing.JTextField();
        jmlkabel_txt1 = new javax.swing.JTextField();
        jmlcctv_txt1 = new javax.swing.JTextField();
        jmlkipas_txt1 = new javax.swing.JTextField();
        jmllampu_txt1 = new javax.swing.JTextField();
        jmlAc_txt1 = new javax.swing.JTextField();
        kondisilampu_label1 = new javax.swing.JLabel();
        posisisteker_label1 = new javax.swing.JLabel();
        kondisiac_label1 = new javax.swing.JLabel();
        kondisikipas_label1 = new javax.swing.JLabel();
        kondisikabel_label1 = new javax.swing.JLabel();
        posisikabel_label1 = new javax.swing.JLabel();
        posisilampu_label1 = new javax.swing.JLabel();
        posisikipas_label1 = new javax.swing.JLabel();
        posisiac_label1 = new javax.swing.JLabel();
        posisicctv_label1 = new javax.swing.JLabel();
        kondisisteker_label1 = new javax.swing.JLabel();
        jmlcctv_txt2 = new javax.swing.JTextField();
        jmlcctv_txt3 = new javax.swing.JTextField();
        jmlcctv_txt4 = new javax.swing.JTextField();
        jmlcctv_txt5 = new javax.swing.JTextField();
        jmlcctv_txt6 = new javax.swing.JTextField();
        jmlcctv_txt7 = new javax.swing.JTextField();
        jmlcctv_txt8 = new javax.swing.JTextField();
        jmlcctv_txt9 = new javax.swing.JTextField();
        jmlcctv_txt10 = new javax.swing.JTextField();
        jmlcctv_txt11 = new javax.swing.JTextField();
        jmlcctv_txt12 = new javax.swing.JTextField();
        jmlcctv_txt13 = new javax.swing.JTextField();
        jmlcctv_txt14 = new javax.swing.JTextField();
        simpan_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Identitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Identitas_button.setText("Identitas Ruang");
        Identitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Identitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 50));

        Fasilitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fasilitas_button.setText("Fasilitas");
        Fasilitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fasilitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Fasilitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, 50));

        Lingkungan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lingkungan_button.setText("Lingkungan");
        Lingkungan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lingkungan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Lingkungan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 50));

        Keamanan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Keamanan_button.setText("Keamanan");
        Keamanan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keamanan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Keamanan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JmlSteker_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        JmlSteker_label.setText("Jumlah Steker");
        jPanel2.add(JmlSteker_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jmlcctv_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlcctv_label.setText("Jumlah CCTV");
        jPanel2.add(jmlcctv_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jmlac_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlac_label.setText("Jumlah AC");
        jPanel2.add(jmlac_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jmllampu_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmllampu_label.setText("Jumlah Lampu");
        jPanel2.add(jmllampu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jmlkipas_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlkipas_label.setText("Jumlah Kipas");
        jPanel2.add(jmlkipas_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        Jmlkabel_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Jmlkabel_label.setText("Jumlah Kabel LCD");
        jPanel2.add(Jmlkabel_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        ssid_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        ssid_label.setText("SSID");
        jPanel2.add(ssid_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        kondisicctv_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisicctv_label.setText("Kondisi CCTV");
        jPanel2.add(kondisicctv_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        JmlSteker_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmlSteker_txtActionPerformed(evt);
            }
        });
        jPanel2.add(JmlSteker_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 106, 22));

        jmlkabel_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkabel_txtActionPerformed(evt);
            }
        });
        jPanel2.add(jmlkabel_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 106, -1));

        jmlcctv_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txtActionPerformed(evt);
            }
        });
        jPanel2.add(jmlcctv_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 106, -1));

        jmlkipas_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkipas_txtActionPerformed(evt);
            }
        });
        jPanel2.add(jmlkipas_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 106, -1));

        jmllampu_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmllampu_txtActionPerformed(evt);
            }
        });
        jPanel2.add(jmllampu_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 106, -1));

        jmlAc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlAc_txtActionPerformed(evt);
            }
        });
        jPanel2.add(jmlAc_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 106, -1));

        kondisicctv_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        jPanel2.add(kondisicctv_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        kondisilampu_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisilampu_label.setText("Kondisi Lampu");
        jPanel2.add(kondisilampu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        posisisteker_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisisteker_label.setText("Posisi Steker");
        jPanel2.add(posisisteker_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        kondisiac_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisiac_label.setText("Kondisi AC");
        jPanel2.add(kondisiac_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        kondisikipas_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisikipas_label.setText("Kondisi Kipas");
        jPanel2.add(kondisikipas_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        ssid_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UMM Hospot", "Lab Informatika" }));
        ssid_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssid_comboActionPerformed(evt);
            }
        });
        jPanel2.add(ssid_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        kondisikipas_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        jPanel2.add(kondisikipas_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        kondisilampu_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        jPanel2.add(kondisilampu_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        kondisikabel_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        jPanel2.add(kondisikabel_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        posisikabel_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pojok Ruang", "Dekat Dosen", "Atap" }));
        posisikabel_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisikabel_comboActionPerformed(evt);
            }
        });
        jPanel2.add(posisikabel_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        kondisikabel_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisikabel_label.setText("Kondisi Kabel LCD");
        jPanel2.add(kondisikabel_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        kondisiac_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        jPanel2.add(kondisiac_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        posisikabel_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisikabel_label.setText("Posisi Kabel LCD");
        jPanel2.add(posisikabel_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        posisilampu_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisilampu_label.setText("Posisi Lampu");
        jPanel2.add(posisilampu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        posisikipas_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisikipas_label.setText("Posisi Kipas");
        jPanel2.add(posisikipas_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        posisiac_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisiac_label.setText("Posisi AC");
        jPanel2.add(posisiac_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        posisicctv_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisicctv_label.setText("Posisi CCTV");
        jPanel2.add(posisicctv_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        kondisisteker_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisisteker_label.setText("Kondisi Steker");
        jPanel2.add(kondisisteker_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        kondisisteker_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        kondisisteker_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisisteker_comboActionPerformed(evt);
            }
        });
        jPanel2.add(kondisisteker_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        posisilampu_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pojok Ruang", "Dekat Dosen", "Atap" }));
        posisilampu_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisilampu_comboActionPerformed(evt);
            }
        });
        jPanel2.add(posisilampu_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        posisikipas_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pojok Ruang", "Dekat Dosen", "Atap" }));
        posisikipas_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisikipas_comboActionPerformed(evt);
            }
        });
        jPanel2.add(posisikipas_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        posisicctv_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Belakang", "Samping", "Depan" }));
        posisicctv_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisicctv_comboActionPerformed(evt);
            }
        });
        jPanel2.add(posisicctv_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        posisisteker_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pojok Ruang", "Dekat Dosen", "Atap" }));
        posisisteker_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisisteker_comboActionPerformed(evt);
            }
        });
        jPanel2.add(posisisteker_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        posisiac_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Belakang", "Atap ", "Depan" }));
        posisiac_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiac_comboActionPerformed(evt);
            }
        });
        jPanel2.add(posisiac_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        jmlampu_button.setText("Analisis");
        jmlampu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlampu_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(jmlampu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jmlsteker_button.setText("Analisis");
        jmlsteker_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlsteker_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(jmlsteker_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jmlkipas_button.setText("Analisis");
        jmlkipas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkipas_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(jmlkipas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jmlac_button.setText("Analisis");
        jmlac_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlac_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(jmlac_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        ssid_button.setText("Analisis");
        ssid_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssid_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(ssid_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jmlkabel_button.setText("Analisis");
        jmlkabel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkabel_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(jmlkabel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        kondisisteker_button.setText("Analisis");
        kondisisteker_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisisteker_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(kondisisteker_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        kondisilampu_button.setText("Analisis");
        kondisilampu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisilampu_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(kondisilampu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jmlcctv_button.setText("Analisis");
        jmlcctv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(jmlcctv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        kondisikipas_button.setText("Analisis");
        kondisikipas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisikipas_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(kondisikipas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        kondisiac_button.setText("Analisis");
        kondisiac_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisiac_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(kondisiac_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        posisicctv_button.setText("Analisis");
        posisicctv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisicctv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(posisicctv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, -1));

        kondisikabel_button.setText("Analisis");
        kondisikabel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisikabel_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(kondisikabel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        posisiac_button.setText("Analisis");
        posisiac_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiac_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(posisiac_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        posisikipas_button.setText("Analisis");
        posisikipas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisikipas_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(posisikipas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        posisilampu_button.setText("Analisis");
        posisilampu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisilampu_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(posisilampu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        posisikabel_button.setText("Analisis");
        posisikabel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisikabel_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(posisikabel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        posisisteker_button.setText("Analisis");
        posisisteker_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisisteker_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(posisisteker_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        kondisicctv_button.setText("Analisis");
        kondisicctv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisicctv_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(kondisicctv_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 620));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JmlSteker_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        JmlSteker_label1.setText("Jumlah Steker");
        jPanel3.add(JmlSteker_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jmlcctv_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlcctv_label1.setText("Jumlah CCTV");
        jPanel3.add(jmlcctv_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jmlac_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlac_label1.setText("Jumlah AC");
        jPanel3.add(jmlac_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jmllampu_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmllampu_label1.setText("Jumlah Lampu");
        jPanel3.add(jmllampu_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jmlkipas_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlkipas_label1.setText("Jumlah Kipas");
        jPanel3.add(jmlkipas_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        Jmlkabel_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Jmlkabel_label1.setText("Jumlah Kabel LCD");
        jPanel3.add(Jmlkabel_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        ssid_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        ssid_label1.setText("SSID");
        jPanel3.add(ssid_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        kondisicctv_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisicctv_label1.setText("Kondisi CCTV");
        jPanel3.add(kondisicctv_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        JmlSteker_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmlSteker_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(JmlSteker_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 106, 22));

        jmlkabel_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkabel_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlkabel_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 106, -1));

        jmlcctv_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 106, -1));

        jmlkipas_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlkipas_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlkipas_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 106, -1));

        jmllampu_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmllampu_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jmllampu_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 106, -1));

        jmlAc_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlAc_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlAc_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 106, -1));

        kondisilampu_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisilampu_label1.setText("Kondisi Lampu");
        jPanel3.add(kondisilampu_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        posisisteker_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisisteker_label1.setText("Posisi Steker");
        jPanel3.add(posisisteker_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        kondisiac_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisiac_label1.setText("Kondisi AC");
        jPanel3.add(kondisiac_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        kondisikipas_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisikipas_label1.setText("Kondisi Kipas");
        jPanel3.add(kondisikipas_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        kondisikabel_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisikabel_label1.setText("Kondisi Kabel LCD");
        jPanel3.add(kondisikabel_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        posisikabel_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisikabel_label1.setText("Posisi Kabel LCD");
        jPanel3.add(posisikabel_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        posisilampu_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisilampu_label1.setText("Posisi Lampu");
        jPanel3.add(posisilampu_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        posisikipas_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisikipas_label1.setText("Posisi Kipas");
        jPanel3.add(posisikipas_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        posisiac_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisiac_label1.setText("Posisi AC");
        jPanel3.add(posisiac_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        posisicctv_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        posisicctv_label1.setText("Posisi CCTV");
        jPanel3.add(posisicctv_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        kondisisteker_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kondisisteker_label1.setText("Kondisi Steker");
        jPanel3.add(kondisisteker_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jmlcctv_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt2ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 106, -1));

        jmlcctv_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt3ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 106, -1));

        jmlcctv_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt4ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 106, -1));

        jmlcctv_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt5ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 106, -1));

        jmlcctv_txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt6ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 106, -1));

        jmlcctv_txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt7ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 106, -1));

        jmlcctv_txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt8ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 106, -1));

        jmlcctv_txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt9ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 106, -1));

        jmlcctv_txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt10ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 106, -1));

        jmlcctv_txt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt11ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 106, -1));

        jmlcctv_txt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt12ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 106, -1));

        jmlcctv_txt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt13ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 106, -1));

        jmlcctv_txt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlcctv_txt14ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlcctv_txt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 106, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 270, 620));

        simpan_button.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        simpan_button.setText("Simpan");
        simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(simpan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Identitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identitas_buttonActionPerformed
        Identitas_gui identitas = new  Identitas_gui();
        identitas.Identitas_gui();
    }//GEN-LAST:event_Identitas_buttonActionPerformed

    private void Fasilitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fasilitas_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fasilitas_buttonActionPerformed

    private void posisikabel_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisikabel_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisikabel_comboActionPerformed

    private void posisilampu_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisilampu_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisilampu_comboActionPerformed

    private void posisikipas_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisikipas_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisikipas_comboActionPerformed

    private void posisicctv_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisicctv_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisicctv_comboActionPerformed

    private void posisisteker_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisisteker_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisisteker_comboActionPerformed

    private void posisiac_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisiac_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisiac_comboActionPerformed

    private void Lingkungan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lingkungan_buttonActionPerformed
        Lingkungan_gui lingkungan = new Lingkungan_gui();
        lingkungan.Lingkungan_gui();
    }//GEN-LAST:event_Lingkungan_buttonActionPerformed

    private void Keamanan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keamanan_buttonActionPerformed
        Kenyamanan_gui kenyamanan = new Kenyamanan_gui();
        kenyamanan.Kenyamanan_gui();
    }//GEN-LAST:event_Keamanan_buttonActionPerformed

    private void JmlSteker_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmlSteker_txtActionPerformed
        
    }//GEN-LAST:event_JmlSteker_txtActionPerformed

    private void jmlkabel_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkabel_txtActionPerformed
        
    }//GEN-LAST:event_jmlkabel_txtActionPerformed

    private void jmllampu_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmllampu_txtActionPerformed
        
    }//GEN-LAST:event_jmllampu_txtActionPerformed

    private void jmlkipas_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkipas_txtActionPerformed
        
    }//GEN-LAST:event_jmlkipas_txtActionPerformed

    private void jmlAc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlAc_txtActionPerformed
        
    }//GEN-LAST:event_jmlAc_txtActionPerformed

    private void jmlcctv_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txtActionPerformed
        
    }//GEN-LAST:event_jmlcctv_txtActionPerformed

    private void ssid_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssid_comboActionPerformed
        //input.setSSID(Integer.parseInt(ssid_combo.));
    }//GEN-LAST:event_ssid_comboActionPerformed

    private void simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_buttonActionPerformed
        
        
        
        input.setPilih_kondisilampu(kondisilampu_combo.getSelectedIndex());
        input.setPilih_kondisikipas(kondisikipas_combo.getSelectedIndex());
        input.setPilih_posisiac(kondisiac_combo.getSelectedIndex());
        input.setPilih_kondisicctv(kondisicctv_combo.getSelectedIndex());
        input.setPosisisteker(posisisteker_combo.getSelectedIndex());
        input.setPilih_posisikabel(posisikabel_combo.getSelectedIndex());
        input.setPilih_posisilampu(posisilampu_combo.getSelectedIndex());
        input.setPilih_posisikipas(posisikipas_combo.getSelectedIndex());
        input.setPilih_posisiac(posisiac_combo.getSelectedIndex());
        input.setPosisiCCTV(posisicctv_combo.getSelectedIndex());
        input.setJumlahsteker(Integer.parseInt(JmlSteker_txt.getText()));
        input.setJumlahkabelLCD(Integer.parseInt(jmlkabel_txt.getText()));
        input.setJumlahlampu(Integer.parseInt(jmllampu_txt.getText()));
        input.setJumlahkipasangin(Integer.parseInt(jmlkabel_txt.getText()));
        input.setJumlahAC(Integer.parseInt(jmlAc_txt.getText()));
        input.setJumlahCCTV(Integer.parseInt(jmlcctv_txt.getText()));
    }//GEN-LAST:event_simpan_buttonActionPerformed

    private void kondisisteker_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisisteker_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kondisisteker_comboActionPerformed

    private void jmlampu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlampu_buttonActionPerformed
        input.setJumlahlampu(Integer.parseInt(jmllampu_txt.getText()));
        input.JumlahLampu();
    }//GEN-LAST:event_jmlampu_buttonActionPerformed

    private void jmlsteker_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlsteker_buttonActionPerformed
        input.setJumlahsteker(Integer.parseInt(JmlSteker_txt.getText()));
        input.JumlahSteker();
    }//GEN-LAST:event_jmlsteker_buttonActionPerformed

    private void jmlkipas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkipas_buttonActionPerformed
        input.setJumlahkipasangin(Integer.parseInt(jmlkipas_txt.getText()));
        input.JumlahKipasAngin();
    }//GEN-LAST:event_jmlkipas_buttonActionPerformed

    private void jmlac_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlac_buttonActionPerformed
        input.setJumlahAC(Integer.parseInt(jmlAc_txt.getText()));
        input.JumlahAC();
    }//GEN-LAST:event_jmlac_buttonActionPerformed

    private void ssid_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssid_buttonActionPerformed
        input.setSSID(ssid_combo.getSelectedIndex());
        input.SSID();
    }//GEN-LAST:event_ssid_buttonActionPerformed

    private void jmlkabel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkabel_buttonActionPerformed
        input.setJumlahkabelLCD(Integer.parseInt(jmlkabel_txt.getText()));
        input.JumlahKabelLCD();
    }//GEN-LAST:event_jmlkabel_buttonActionPerformed

    private void kondisisteker_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisisteker_buttonActionPerformed
        input.setPilih_kondisisteker(kondisisteker_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string1();
    }//GEN-LAST:event_kondisisteker_buttonActionPerformed

    private void kondisilampu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisilampu_buttonActionPerformed
        input.setPilih_kondisilampu(kondisilampu_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string3();
    }//GEN-LAST:event_kondisilampu_buttonActionPerformed

    private void jmlcctv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_buttonActionPerformed
        input.setJumlahCCTV(Integer.parseInt(jmlcctv_txt.getText()));
        input.JumlahCCTV();
    }//GEN-LAST:event_jmlcctv_buttonActionPerformed

    private void kondisikipas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisikipas_buttonActionPerformed
        input.setPilih_kondisikipas(kondisikipas_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string4();
    }//GEN-LAST:event_kondisikipas_buttonActionPerformed

    private void kondisiac_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisiac_buttonActionPerformed
        input.setPilih_kondisiac(kondisiac_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string5();
    }//GEN-LAST:event_kondisiac_buttonActionPerformed

    private void posisicctv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisicctv_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisicctv_buttonActionPerformed

    private void kondisikabel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisikabel_buttonActionPerformed
        input.setPilih_kondisikabel(kondisikabel_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string2();
    }//GEN-LAST:event_kondisikabel_buttonActionPerformed

    private void posisiac_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisiac_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisiac_buttonActionPerformed

    private void posisikipas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisikipas_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisikipas_buttonActionPerformed

    private void posisilampu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisilampu_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisilampu_buttonActionPerformed

    private void posisikabel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisikabel_buttonActionPerformed
        input.setPilih_kondisikabel(kondisikabel_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string2();
    }//GEN-LAST:event_posisikabel_buttonActionPerformed

    private void posisisteker_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisisteker_buttonActionPerformed
        input.setPosisisteker(posisisteker_combo.getSelectedIndex());
        input.posisiSteker();
    }//GEN-LAST:event_posisisteker_buttonActionPerformed

    private void kondisicctv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisicctv_buttonActionPerformed
        input.setPilih_kondisicctv(kondisicctv_combo.getSelectedIndex());
        input.setFasilitas(0, 0, 0, 0, 0, 0);
        input.string6();
    }//GEN-LAST:event_kondisicctv_buttonActionPerformed

    private void JmlSteker_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmlSteker_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmlSteker_txt1ActionPerformed

    private void jmlkabel_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkabel_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlkabel_txt1ActionPerformed

    private void jmlcctv_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt1ActionPerformed

    private void jmlkipas_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlkipas_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlkipas_txt1ActionPerformed

    private void jmllampu_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmllampu_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmllampu_txt1ActionPerformed

    private void jmlAc_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlAc_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlAc_txt1ActionPerformed

    private void jmlcctv_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt2ActionPerformed

    private void jmlcctv_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt3ActionPerformed

    private void jmlcctv_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt4ActionPerformed

    private void jmlcctv_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt5ActionPerformed

    private void jmlcctv_txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt6ActionPerformed

    private void jmlcctv_txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt7ActionPerformed

    private void jmlcctv_txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt8ActionPerformed

    private void jmlcctv_txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt9ActionPerformed

    private void jmlcctv_txt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt10ActionPerformed

    private void jmlcctv_txt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt11ActionPerformed

    private void jmlcctv_txt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt12ActionPerformed

    private void jmlcctv_txt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt13ActionPerformed

    private void jmlcctv_txt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlcctv_txt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlcctv_txt14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Fasilitas_GUI(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fasilitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fasilitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fasilitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fasilitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
                new Fasilitas_GUI().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fasilitas_button;
    private javax.swing.JButton Identitas_button;
    private javax.swing.JLabel JmlSteker_label;
    private javax.swing.JLabel JmlSteker_label1;
    private javax.swing.JTextField JmlSteker_txt;
    private javax.swing.JTextField JmlSteker_txt1;
    private javax.swing.JLabel Jmlkabel_label;
    private javax.swing.JLabel Jmlkabel_label1;
    private javax.swing.JButton Keamanan_button;
    private javax.swing.JButton Lingkungan_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jmlAc_txt;
    private javax.swing.JTextField jmlAc_txt1;
    private javax.swing.JButton jmlac_button;
    private javax.swing.JLabel jmlac_label;
    private javax.swing.JLabel jmlac_label1;
    private javax.swing.JButton jmlampu_button;
    private javax.swing.JButton jmlcctv_button;
    private javax.swing.JLabel jmlcctv_label;
    private javax.swing.JLabel jmlcctv_label1;
    private javax.swing.JTextField jmlcctv_txt;
    private javax.swing.JTextField jmlcctv_txt1;
    private javax.swing.JTextField jmlcctv_txt10;
    private javax.swing.JTextField jmlcctv_txt11;
    private javax.swing.JTextField jmlcctv_txt12;
    private javax.swing.JTextField jmlcctv_txt13;
    private javax.swing.JTextField jmlcctv_txt14;
    private javax.swing.JTextField jmlcctv_txt2;
    private javax.swing.JTextField jmlcctv_txt3;
    private javax.swing.JTextField jmlcctv_txt4;
    private javax.swing.JTextField jmlcctv_txt5;
    private javax.swing.JTextField jmlcctv_txt6;
    private javax.swing.JTextField jmlcctv_txt7;
    private javax.swing.JTextField jmlcctv_txt8;
    private javax.swing.JTextField jmlcctv_txt9;
    private javax.swing.JButton jmlkabel_button;
    private javax.swing.JTextField jmlkabel_txt;
    private javax.swing.JTextField jmlkabel_txt1;
    private javax.swing.JButton jmlkipas_button;
    private javax.swing.JLabel jmlkipas_label;
    private javax.swing.JLabel jmlkipas_label1;
    private javax.swing.JTextField jmlkipas_txt;
    private javax.swing.JTextField jmlkipas_txt1;
    private javax.swing.JLabel jmllampu_label;
    private javax.swing.JLabel jmllampu_label1;
    private javax.swing.JTextField jmllampu_txt;
    private javax.swing.JTextField jmllampu_txt1;
    private javax.swing.JButton jmlsteker_button;
    private javax.swing.JButton kondisiac_button;
    private javax.swing.JComboBox kondisiac_combo;
    private javax.swing.JLabel kondisiac_label;
    private javax.swing.JLabel kondisiac_label1;
    private javax.swing.JButton kondisicctv_button;
    private javax.swing.JComboBox kondisicctv_combo;
    private javax.swing.JLabel kondisicctv_label;
    private javax.swing.JLabel kondisicctv_label1;
    private javax.swing.JButton kondisikabel_button;
    private javax.swing.JComboBox kondisikabel_combo;
    private javax.swing.JLabel kondisikabel_label;
    private javax.swing.JLabel kondisikabel_label1;
    private javax.swing.JButton kondisikipas_button;
    private javax.swing.JComboBox kondisikipas_combo;
    private javax.swing.JLabel kondisikipas_label;
    private javax.swing.JLabel kondisikipas_label1;
    private javax.swing.JButton kondisilampu_button;
    private javax.swing.JComboBox kondisilampu_combo;
    private javax.swing.JLabel kondisilampu_label;
    private javax.swing.JLabel kondisilampu_label1;
    private javax.swing.JButton kondisisteker_button;
    private javax.swing.JComboBox kondisisteker_combo;
    private javax.swing.JLabel kondisisteker_label;
    private javax.swing.JLabel kondisisteker_label1;
    private javax.swing.JButton posisiac_button;
    private javax.swing.JComboBox posisiac_combo;
    private javax.swing.JLabel posisiac_label;
    private javax.swing.JLabel posisiac_label1;
    private javax.swing.JButton posisicctv_button;
    private javax.swing.JComboBox posisicctv_combo;
    private javax.swing.JLabel posisicctv_label;
    private javax.swing.JLabel posisicctv_label1;
    private javax.swing.JButton posisikabel_button;
    private javax.swing.JComboBox posisikabel_combo;
    private javax.swing.JLabel posisikabel_label;
    private javax.swing.JLabel posisikabel_label1;
    private javax.swing.JButton posisikipas_button;
    private javax.swing.JComboBox posisikipas_combo;
    private javax.swing.JLabel posisikipas_label;
    private javax.swing.JLabel posisikipas_label1;
    private javax.swing.JButton posisilampu_button;
    private javax.swing.JComboBox posisilampu_combo;
    private javax.swing.JLabel posisilampu_label;
    private javax.swing.JLabel posisilampu_label1;
    private javax.swing.JButton posisisteker_button;
    private javax.swing.JComboBox posisisteker_combo;
    private javax.swing.JLabel posisisteker_label;
    private javax.swing.JLabel posisisteker_label1;
    private javax.swing.JButton simpan_button;
    private javax.swing.JButton ssid_button;
    private javax.swing.JComboBox ssid_combo;
    private javax.swing.JLabel ssid_label;
    private javax.swing.JLabel ssid_label1;
    // End of variables declaration//GEN-END:variables
}
