/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author NirmalaKarim
 */
public class Identitas_gui extends javax.swing.JFrame {
    Input_identitas input = new Input_identitas();
    /**
     * Creates new form Identitas_gui
     */
    public Identitas_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Identitas_button = new javax.swing.JButton();
        Fasilitas_button = new javax.swing.JButton();
        Lingkungan_button = new javax.swing.JButton();
        Keamanan_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Nama_label = new javax.swing.JLabel();
        jmlKursi_label = new javax.swing.JLabel();
        Lokasi_label = new javax.swing.JLabel();
        Panjang_label = new javax.swing.JLabel();
        Lebar_label = new javax.swing.JLabel();
        Jurusan_label = new javax.swing.JLabel();
        JmlJendela_label = new javax.swing.JLabel();
        jmlPintu_label = new javax.swing.JLabel();
        Nama_tampil = new javax.swing.JTextField();
        jurusan_tampil = new javax.swing.JTextField();
        jumlahkursi_tampil = new javax.swing.JTextField();
        panjang_tampil = new javax.swing.JTextField();
        lokasi_tampil = new javax.swing.JTextField();
        jumlahjendela_tampil = new javax.swing.JTextField();
        lebar_tampil = new javax.swing.JTextField();
        jumlahpintu_tampil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Nama_label1 = new javax.swing.JLabel();
        luas_label = new javax.swing.JLabel();
        Lokasi_label1 = new javax.swing.JLabel();
        Panjang_label1 = new javax.swing.JLabel();
        Lebar_label1 = new javax.swing.JLabel();
        Jurusan_label1 = new javax.swing.JLabel();
        JmlJendela_label1 = new javax.swing.JLabel();
        jmlPintu_label1 = new javax.swing.JLabel();
        Nama_txt1 = new javax.swing.JTextField();
        jurusan_txt1 = new javax.swing.JTextField();
        panjang_txt1 = new javax.swing.JTextField();
        lokasi_txt1 = new javax.swing.JTextField();
        lebar_txt1 = new javax.swing.JTextField();
        jumlahkursi_txt1 = new javax.swing.JTextField();
        luas_txt = new javax.swing.JTextField();
        jmljendela_txt3 = new javax.swing.JTextField();
        Luas_button = new javax.swing.JButton();
        jmlpintu_txt4 = new javax.swing.JTextField();
        rasio_txt = new javax.swing.JTextField();
        jmlKursi_label3 = new javax.swing.JLabel();
        rasio_label = new javax.swing.JLabel();
        jmlpintu_button = new javax.swing.JButton();
        rasio_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setMaximumSize(new java.awt.Dimension(20, 20));
        setMinimumSize(new java.awt.Dimension(20, 20));
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Identitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Identitas_button.setText("Identitas Ruang");
        Identitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Identitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 50));

        Fasilitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fasilitas_button.setText("Fasilitas");
        Fasilitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fasilitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Fasilitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, 50));

        Lingkungan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lingkungan_button.setText("Lingkungan");
        Lingkungan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lingkungan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Lingkungan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 50));

        Keamanan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Keamanan_button.setText("Keamanan");
        Keamanan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keamanan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Keamanan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nama_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Nama_label.setText("Nama Ruang");
        jPanel2.add(Nama_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jmlKursi_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlKursi_label.setText("Jumlah Kursi");
        jPanel2.add(jmlKursi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        Lokasi_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Lokasi_label.setText("Lokasi Ruang");
        jPanel2.add(Lokasi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        Panjang_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Panjang_label.setText("Panjang Ruang");
        jPanel2.add(Panjang_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Lebar_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Lebar_label.setText("Lebar Ruang");
        jPanel2.add(Lebar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        Jurusan_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Jurusan_label.setText("Jurusan");
        jPanel2.add(Jurusan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        JmlJendela_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        JmlJendela_label.setText("Jumlah Jendela");
        jPanel2.add(JmlJendela_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jmlPintu_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlPintu_label.setText("Jumlah Pintu");
        jPanel2.add(jmlPintu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        Nama_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(Nama_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 106, 22));

        jurusan_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusan_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(jurusan_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 106, -1));

        jumlahkursi_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahkursi_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(jumlahkursi_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 106, -1));

        panjang_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjang_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(panjang_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 106, -1));

        lokasi_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasi_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(lokasi_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 106, -1));

        jumlahjendela_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahjendela_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(jumlahjendela_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, -1));

        lebar_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebar_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(lebar_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 106, -1));

        jumlahpintu_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahpintu_tampilActionPerformed(evt);
            }
        });
        jPanel2.add(jumlahpintu_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 240, 260));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 120, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nama_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Nama_label1.setText("Nama Ruang");
        jPanel3.add(Nama_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        luas_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        luas_label.setText("Luas");
        jPanel3.add(luas_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        Lokasi_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Lokasi_label1.setText("Lokasi Ruang");
        jPanel3.add(Lokasi_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        Panjang_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Panjang_label1.setText("Panjang Ruang");
        jPanel3.add(Panjang_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Lebar_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Lebar_label1.setText("Lebar Ruang");
        jPanel3.add(Lebar_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        Jurusan_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Jurusan_label1.setText("Jurusan");
        jPanel3.add(Jurusan_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        JmlJendela_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        JmlJendela_label1.setText("Jumlah Jendela");
        jPanel3.add(JmlJendela_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jmlPintu_label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlPintu_label1.setText("Jumlah Pintu");
        jPanel3.add(jmlPintu_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        Nama_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(Nama_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 106, 22));

        jurusan_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusan_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jurusan_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 106, -1));

        panjang_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjang_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(panjang_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 106, -1));

        lokasi_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasi_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(lokasi_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 106, -1));

        lebar_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebar_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(lebar_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 106, -1));

        jumlahkursi_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahkursi_txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(jumlahkursi_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 106, -1));

        luas_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luas_txtActionPerformed(evt);
            }
        });
        jPanel3.add(luas_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 106, -1));

        jmljendela_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmljendela_txt3ActionPerformed(evt);
            }
        });
        jPanel3.add(jmljendela_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 106, -1));

        Luas_button.setText("Hitung");
        Luas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Luas_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(Luas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, 20));

        jmlpintu_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlpintu_txt4ActionPerformed(evt);
            }
        });
        jPanel3.add(jmlpintu_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 106, -1));

        rasio_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasio_txtActionPerformed(evt);
            }
        });
        jPanel3.add(rasio_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 106, -1));

        jmlKursi_label3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jmlKursi_label3.setText("Jumlah Kursi");
        jPanel3.add(jmlKursi_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        rasio_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        rasio_label.setText("Rasio");
        jPanel3.add(rasio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jmlpintu_button.setText("Analisis");
        jmlpintu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlpintu_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(jmlpintu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 70, 50));

        rasio_button.setText("Hitung");
        rasio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasio_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(rasio_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 80, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Identitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identitas_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Identitas_buttonActionPerformed
Fasilitas_GUI fasilitas = new Fasilitas_GUI();
    private void Fasilitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fasilitas_buttonActionPerformed
        fasilitas.Fasilitas_GUI();
    }//GEN-LAST:event_Fasilitas_buttonActionPerformed
Lingkungan_gui lingkung = new  Lingkungan_gui();
    private void Lingkungan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lingkungan_buttonActionPerformed
        
        lingkung.Lingkungan_gui();
    }//GEN-LAST:event_Lingkungan_buttonActionPerformed
Kenyamanan_gui keamanan = new Kenyamanan_gui();
    private void Keamanan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keamanan_buttonActionPerformed
        // TODO add your handling code here:
        
        keamanan.Kenyamanan_gui();
    }//GEN-LAST:event_Keamanan_buttonActionPerformed

    private void Nama_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_tampilActionPerformed
        
    }//GEN-LAST:event_Nama_tampilActionPerformed

    private void jurusan_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusan_tampilActionPerformed
        
    }//GEN-LAST:event_jurusan_tampilActionPerformed

    private void lokasi_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasi_tampilActionPerformed
        
    }//GEN-LAST:event_lokasi_tampilActionPerformed

    private void panjang_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjang_tampilActionPerformed
        
    }//GEN-LAST:event_panjang_tampilActionPerformed

    private void lebar_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebar_tampilActionPerformed
        
    }//GEN-LAST:event_lebar_tampilActionPerformed

    private void jumlahkursi_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahkursi_tampilActionPerformed
        
    }//GEN-LAST:event_jumlahkursi_tampilActionPerformed

    private void jumlahjendela_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahjendela_tampilActionPerformed
        
    }//GEN-LAST:event_jumlahjendela_tampilActionPerformed

    private void jumlahpintu_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahpintu_tampilActionPerformed
        
    }//GEN-LAST:event_jumlahpintu_tampilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Nama_tampil.setText(Nama_txt1.getText());
        lokasi_tampil.setText(lokasi_txt1.getText());
        jurusan_tampil.setText(jurusan_txt1.getText());
        panjang_tampil.setText(panjang_txt1.getText());
        lebar_tampil.setText(lebar_txt1.getText());
        jumlahkursi_tampil.setText(jumlahkursi_txt1.getText());
        jumlahpintu_tampil.setText(jmlpintu_txt4.getText());
        jumlahjendela_tampil.setText(jmljendela_txt3.getText());
        jumlahpintu_tampil.setText(jmlpintu_txt4.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Nama_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_txt1ActionPerformed
        input.setNama_ruang(Nama_txt1.getText());
    }//GEN-LAST:event_Nama_txt1ActionPerformed

    private void jurusan_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusan_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusan_txt1ActionPerformed

    private void jumlahkursi_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahkursi_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahkursi_txt1ActionPerformed

    private void panjang_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjang_txt1ActionPerformed
        
    }//GEN-LAST:event_panjang_txt1ActionPerformed

    private void lokasi_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasi_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasi_txt1ActionPerformed

    private void lebar_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebar_txt1ActionPerformed
        
    }//GEN-LAST:event_lebar_txt1ActionPerformed

    private void luas_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luas_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luas_txtActionPerformed

    private void jmljendela_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmljendela_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmljendela_txt3ActionPerformed

    private void Luas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Luas_buttonActionPerformed
        input.setPanjang_ruang(Integer.parseInt(panjang_txt1.getText()));
        input.setLebar_ruang(Integer.parseInt(lebar_txt1.getText()));
        input.luas();
        luas_txt.setText(Double.toString(input.luas()));
        
    }//GEN-LAST:event_Luas_buttonActionPerformed

    private void jmlpintu_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlpintu_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlpintu_txt4ActionPerformed

    private void rasio_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasio_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rasio_txtActionPerformed

    private void jmlpintu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlpintu_buttonActionPerformed
        input.setJumlah_jendela(Integer.parseInt(jmljendela_txt3.getText()));
        input.setJumlah_pintu(Integer.parseInt(jmlpintu_txt4.getText()));
        input.analisisPintuDanJendela();
        
    }//GEN-LAST:event_jmlpintu_buttonActionPerformed

    private void rasio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasio_buttonActionPerformed
        input.Analisis_rasio();
        input.setJumlah_kursi(Integer.parseInt(jumlahkursi_txt1.getText()));
        input.rasio();
        rasio_txt.setText(Double.toString(input.rasio()));
    }//GEN-LAST:event_rasio_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void Identitas_gui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identitas_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identitas_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identitas_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identitas_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

                new Identitas_gui().setVisible(true);
     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fasilitas_button;
    private javax.swing.JButton Identitas_button;
    private javax.swing.JLabel JmlJendela_label;
    private javax.swing.JLabel JmlJendela_label1;
    private javax.swing.JLabel Jurusan_label;
    private javax.swing.JLabel Jurusan_label1;
    private javax.swing.JButton Keamanan_button;
    private javax.swing.JLabel Lebar_label;
    private javax.swing.JLabel Lebar_label1;
    private javax.swing.JButton Lingkungan_button;
    private javax.swing.JLabel Lokasi_label;
    private javax.swing.JLabel Lokasi_label1;
    private javax.swing.JButton Luas_button;
    private javax.swing.JLabel Nama_label;
    private javax.swing.JLabel Nama_label1;
    private javax.swing.JTextField Nama_tampil;
    public javax.swing.JTextField Nama_txt1;
    private javax.swing.JLabel Panjang_label;
    private javax.swing.JLabel Panjang_label1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jmlKursi_label;
    private javax.swing.JLabel jmlKursi_label3;
    private javax.swing.JLabel jmlPintu_label;
    private javax.swing.JLabel jmlPintu_label1;
    private javax.swing.JTextField jmljendela_txt3;
    private javax.swing.JButton jmlpintu_button;
    private javax.swing.JTextField jmlpintu_txt4;
    private javax.swing.JTextField jumlahjendela_tampil;
    private javax.swing.JTextField jumlahkursi_tampil;
    private javax.swing.JTextField jumlahkursi_txt1;
    private javax.swing.JTextField jumlahpintu_tampil;
    private javax.swing.JTextField jurusan_tampil;
    private javax.swing.JTextField jurusan_txt1;
    private javax.swing.JTextField lebar_tampil;
    private javax.swing.JTextField lebar_txt1;
    private javax.swing.JTextField lokasi_tampil;
    private javax.swing.JTextField lokasi_txt1;
    private javax.swing.JLabel luas_label;
    private javax.swing.JTextField luas_txt;
    private javax.swing.JTextField panjang_tampil;
    private javax.swing.JTextField panjang_txt1;
    private javax.swing.JButton rasio_button;
    private javax.swing.JLabel rasio_label;
    private javax.swing.JTextField rasio_txt;
    // End of variables declaration//GEN-END:variables
}
