/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author NirmalaKarim
 */
public class Kenyamanan_gui extends javax.swing.JFrame {

    /**
     * Creates new form Lingkungan_gui
     */
    public Kenyamanan_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Identitas_button = new javax.swing.JButton();
        Fasilitas_button = new javax.swing.JButton();
        Lingkungan_button = new javax.swing.JButton();
        Keamanan_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Kebisingan_label = new javax.swing.JLabel();
        kerusakan = new javax.swing.JLabel();
        kebocoran_label = new javax.swing.JLabel();
        Keausan_label = new javax.swing.JLabel();
        Bau_label = new javax.swing.JLabel();
        kuncijendela_label = new javax.swing.JLabel();
        bahaya_label = new javax.swing.JLabel();
        bahaya_combo = new javax.swing.JComboBox();
        kuncipintu_label = new javax.swing.JLabel();
        kekokohan_label = new javax.swing.JLabel();
        bau_combo = new javax.swing.JComboBox();
        kebocoran_combo1 = new javax.swing.JComboBox();
        keausan_combo2 = new javax.swing.JComboBox();
        kerusakan_combo = new javax.swing.JComboBox();
        kebisingan_combo4 = new javax.swing.JComboBox();
        kuncijendela_combo1 = new javax.swing.JComboBox();
        kuncipintu_combo = new javax.swing.JComboBox();
        kekokohan_combo3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Penyimpanan_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Identitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Identitas_button.setText("Identitas Ruang");
        Identitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Identitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 50));

        Fasilitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fasilitas_button.setText("Fasilitas");
        Fasilitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fasilitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Fasilitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, 50));

        Lingkungan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lingkungan_button.setText("Lingkungan");
        Lingkungan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lingkungan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Lingkungan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 50));

        Keamanan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Keamanan_button.setText("Kenyamanan");
        Keamanan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keamanan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Keamanan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Kebisingan_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Kebisingan_label.setText("Kebisingan");
        jPanel2.add(Kebisingan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        kerusakan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kerusakan.setText("Kerusakan");
        jPanel2.add(kerusakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        kebocoran_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kebocoran_label.setText("Kebocoran");
        jPanel2.add(kebocoran_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        Keausan_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Keausan_label.setText("Keausan");
        jPanel2.add(Keausan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        Bau_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Bau_label.setText("Bau");
        jPanel2.add(Bau_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        kuncijendela_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kuncijendela_label.setText("Kunci Jendela");
        jPanel2.add(kuncijendela_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        bahaya_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        bahaya_label.setText("Bahaya");
        jPanel2.add(bahaya_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        bahaya_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lancar", "Tidak Lancar" }));
        jPanel2.add(bahaya_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        kuncipintu_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kuncipintu_label.setText("Kunci Pintu");
        jPanel2.add(kuncipintu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        kekokohan_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        kekokohan_label.setText("Kekokohan");
        jPanel2.add(kekokohan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        bau_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bau", "Tidak Bau" }));
        jPanel2.add(bau_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        kebocoran_combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ada", "Tidak Ada" }));
        jPanel2.add(kebocoran_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        keausan_combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ada", "Tidak Ada" }));
        jPanel2.add(keausan_combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        kerusakan_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ada", "Tidak Ada" }));
        jPanel2.add(kerusakan_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        kebisingan_combo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bising", "Tidak Bisis" }));
        jPanel2.add(kebisingan_combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        kuncijendela_combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lancar", "Tidak Lancar" }));
        jPanel2.add(kuncijendela_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        kuncipintu_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lancar", "Tidak Lancar" }));
        jPanel2.add(kuncipintu_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        kekokohan_combo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kokoh", "Tidak Kokoh" }));
        jPanel2.add(kekokohan_combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton1.setText("Simpan");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 120, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 620, 280));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton2.setText("Analisis");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        Penyimpanan_button.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Penyimpanan_button.setText("Penyimpanan");
        Penyimpanan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Penyimpanan_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(Penyimpanan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 590, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Identitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identitas_buttonActionPerformed
        Identitas_gui identitas = new Identitas_gui();
        identitas.Identitas_gui();
    }//GEN-LAST:event_Identitas_buttonActionPerformed

    private void Fasilitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fasilitas_buttonActionPerformed
        Fasilitas_GUI fasilitas = new Fasilitas_GUI();
        fasilitas.Fasilitas_GUI();
    }//GEN-LAST:event_Fasilitas_buttonActionPerformed

    private void Keamanan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keamanan_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Keamanan_buttonActionPerformed

    private void Lingkungan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lingkungan_buttonActionPerformed
        Lingkungan_gui lingkungan = new Lingkungan_gui();
        lingkungan.Lingkungan_gui();
    }//GEN-LAST:event_Lingkungan_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Input_identitas input1 = new Input_identitas();
        Input_lingkungan input3 = new Input_lingkungan();
        Analisis_gui tes = new Analisis_gui();
        tes.Analisis_gui();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Penyimpanan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Penyimpanan_buttonActionPerformed
        
    }//GEN-LAST:event_Penyimpanan_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Kenyamanan_gui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kenyamanan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kenyamanan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kenyamanan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kenyamanan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

                new Kenyamanan_gui().setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bau_label;
    private javax.swing.JButton Fasilitas_button;
    private javax.swing.JButton Identitas_button;
    private javax.swing.JButton Keamanan_button;
    private javax.swing.JLabel Keausan_label;
    private javax.swing.JLabel Kebisingan_label;
    private javax.swing.JButton Lingkungan_button;
    private javax.swing.JButton Penyimpanan_button;
    private javax.swing.JComboBox bahaya_combo;
    private javax.swing.JLabel bahaya_label;
    private javax.swing.JComboBox bau_combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox keausan_combo2;
    private javax.swing.JComboBox kebisingan_combo4;
    private javax.swing.JComboBox kebocoran_combo1;
    private javax.swing.JLabel kebocoran_label;
    private javax.swing.JComboBox kekokohan_combo3;
    private javax.swing.JLabel kekokohan_label;
    private javax.swing.JLabel kerusakan;
    private javax.swing.JComboBox kerusakan_combo;
    private javax.swing.JComboBox kuncijendela_combo1;
    private javax.swing.JLabel kuncijendela_label;
    private javax.swing.JComboBox kuncipintu_combo;
    private javax.swing.JLabel kuncipintu_label;
    // End of variables declaration//GEN-END:variables
}
