/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author NirmalaKarim
 */
public class Lingkungan_gui extends javax.swing.JFrame {

    Input_lingkungan input = new Input_lingkungan();
    /**
     * Creates new form Kenyamanan_gui
     */
    public Lingkungan_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Identitas_button = new javax.swing.JButton();
        Fasilitas_button = new javax.swing.JButton();
        Lingkungan_button = new javax.swing.JButton();
        Keamanan_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Lantai_label = new javax.swing.JLabel();
        jendela_label = new javax.swing.JLabel();
        atap_label = new javax.swing.JLabel();
        pintu_labe = new javax.swing.JLabel();
        dinding_label = new javax.swing.JLabel();
        suhu_txt = new javax.swing.JTextField();
        Kelembapan_label = new javax.swing.JLabel();
        Suhu_label = new javax.swing.JLabel();
        sirkulasiudara_combo = new javax.swing.JComboBox();
        Pencayahan_label = new javax.swing.JLabel();
        SirkulasiUdara_label = new javax.swing.JLabel();
        Dinding_combo = new javax.swing.JComboBox();
        Atap_combo1 = new javax.swing.JComboBox();
        pintu_combo2 = new javax.swing.JComboBox();
        jendela_combo3 = new javax.swing.JComboBox();
        lantair_combo4 = new javax.swing.JComboBox();
        kelembapan_txt1 = new javax.swing.JTextField();
        pencayahan_txt2 = new javax.swing.JTextField();
        simpan_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Identitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Identitas_button.setText("Identitas Ruang");
        Identitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Identitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 50));

        Fasilitas_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fasilitas_button.setText("Fasilitas");
        Fasilitas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fasilitas_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Fasilitas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, 50));

        Lingkungan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lingkungan_button.setText("Lingkungan");
        jPanel1.add(Lingkungan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 50));

        Keamanan_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Keamanan_button.setText("Kenyamanan");
        Keamanan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keamanan_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Keamanan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lantai_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Lantai_label.setText("Lantai");
        jPanel2.add(Lantai_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jendela_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jendela_label.setText("Jendela");
        jPanel2.add(jendela_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        atap_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        atap_label.setText("Atap");
        jPanel2.add(atap_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        pintu_labe.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        pintu_labe.setText("Pintu");
        jPanel2.add(pintu_labe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        dinding_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        dinding_label.setText("Dinding");
        jPanel2.add(dinding_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        suhu_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhu_txtActionPerformed(evt);
            }
        });
        jPanel2.add(suhu_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 106, -1));

        Kelembapan_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Kelembapan_label.setText("Kelembapan");
        jPanel2.add(Kelembapan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Suhu_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Suhu_label.setText("Suhu");
        jPanel2.add(Suhu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        sirkulasiudara_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lancar", "Tidak Lancar" }));
        jPanel2.add(sirkulasiudara_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        Pencayahan_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Pencayahan_label.setText("Pencayahan");
        jPanel2.add(Pencayahan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        SirkulasiUdara_label.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        SirkulasiUdara_label.setText("Sirkulasi Udara");
        jPanel2.add(SirkulasiUdara_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        Dinding_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bersih", "Tidak Bersih" }));
        jPanel2.add(Dinding_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        Atap_combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bersih", "Tidak Bersih" }));
        jPanel2.add(Atap_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        pintu_combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bersih", "Tidak Bersih" }));
        jPanel2.add(pintu_combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jendela_combo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bersih", "Tidak Bersih" }));
        jPanel2.add(jendela_combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        lantair_combo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bersih", "Tidak Bersih" }));
        jPanel2.add(lantair_combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        kelembapan_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelembapan_txt1ActionPerformed(evt);
            }
        });
        jPanel2.add(kelembapan_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 106, -1));

        pencayahan_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencayahan_txt2ActionPerformed(evt);
            }
        });
        jPanel2.add(pencayahan_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 106, -1));

        simpan_button.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        simpan_button.setText("Simpan");
        simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(simpan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 120, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 680, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Identitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identitas_buttonActionPerformed
        Identitas_gui identitas = new Identitas_gui();
        identitas.Identitas_gui();
    }//GEN-LAST:event_Identitas_buttonActionPerformed

    private void Fasilitas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fasilitas_buttonActionPerformed
        Fasilitas_GUI fasilitas = new Fasilitas_GUI();
        fasilitas.Fasilitas_GUI();
    }//GEN-LAST:event_Fasilitas_buttonActionPerformed

    private void Keamanan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keamanan_buttonActionPerformed
        Kenyamanan_gui kenyamanan = new Kenyamanan_gui();
        kenyamanan.Kenyamanan_gui();
    }//GEN-LAST:event_Keamanan_buttonActionPerformed

    private void pencayahan_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencayahan_txt2ActionPerformed
        
    }//GEN-LAST:event_pencayahan_txt2ActionPerformed

    private void kelembapan_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelembapan_txt1ActionPerformed
        
    }//GEN-LAST:event_kelembapan_txt1ActionPerformed

    private void suhu_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhu_txtActionPerformed
        
    }//GEN-LAST:event_suhu_txtActionPerformed

    private void simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_buttonActionPerformed
        input.setPilih_lantai(lantair_combo4.getSelectedIndex());
        input.setPilih_dinding(Dinding_combo.getSelectedIndex());
        input.setPilih_atap(Atap_combo1.getSelectedIndex());
        input.setPilih_pintu(pintu_combo2.getSelectedIndex());
        input.setPilih_jendela(jendela_combo3.getSelectedIndex());
        input.setPilih_sirkulasi(sirkulasiudara_combo.getSelectedIndex());
        input.setPencayahan(Integer.parseInt(pencayahan_txt2.getText()));
        input.setKelembapan(Integer.parseInt(kelembapan_txt1.getText()));
        input.setSuhu(Integer.parseInt(suhu_txt.getText()));
    }//GEN-LAST:event_simpan_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Lingkungan_gui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lingkungan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lingkungan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lingkungan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lingkungan_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 
                new Lingkungan_gui().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Atap_combo1;
    private javax.swing.JComboBox Dinding_combo;
    private javax.swing.JButton Fasilitas_button;
    private javax.swing.JButton Identitas_button;
    private javax.swing.JButton Keamanan_button;
    private javax.swing.JLabel Kelembapan_label;
    private javax.swing.JLabel Lantai_label;
    private javax.swing.JButton Lingkungan_button;
    private javax.swing.JLabel Pencayahan_label;
    private javax.swing.JLabel SirkulasiUdara_label;
    private javax.swing.JLabel Suhu_label;
    private javax.swing.JLabel atap_label;
    private javax.swing.JLabel dinding_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jendela_combo3;
    private javax.swing.JLabel jendela_label;
    private javax.swing.JTextField kelembapan_txt1;
    private javax.swing.JComboBox lantair_combo4;
    private javax.swing.JTextField pencayahan_txt2;
    private javax.swing.JComboBox pintu_combo2;
    private javax.swing.JLabel pintu_labe;
    private javax.swing.JButton simpan_button;
    private javax.swing.JComboBox sirkulasiudara_combo;
    private javax.swing.JTextField suhu_txt;
    // End of variables declaration//GEN-END:variables
}
